version: "3.9"
services:
  tsensor:
    devices:
    - /dev/colibri-uarta:/dev/ttyS1
    - /dev/rs485:/dev/rs485:rw,optional
    image: rafaelkcosta/tsensor:latest
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - /var/log/tsensor_output:/home/torizon/app/src/output
    ports:
    - 5000:5000
  nginx:
    image: rafaelkcosta/nginx_tsensor:latest
    volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    container_name: nginx_tsensor
    depends_on:
    - tsensor
    ports:
    - 80:80
