services:
  tsensor:
    image: rafaelkcosta/tsensor:latest
    devices:
    - /dev/colibri-uarta:/dev/ttyS1
    ports:
    - 5000:5000
  nginx:
    image: rafaelkcosta/nginx_tsensor:latest
    depends_on:
    - tsensor
    ports:
    - 80:80
    container_name: nginx_tsensor
version: "3.9"
