version: "3.9"
services:
  tsensor-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/tsensor-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
      - 5000:5000
    devices:
      - "/dev/colibri-uarta:/dev/ttyS1"
    
  tsensor:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/tsensor:${TAG}
    ports:
      - 5000:5000    
    devices:
      - "/dev/colibri-uarta:/dev/ttyS1"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: ${DOCKER_LOGIN}/nginx_tsensor:${TAG}
    container_name: nginx_tsensor
    ports:
      - "80:80"
    depends_on:
      - tsensor